In [1]:
import numpy as np
import pandas as pd

In [15]:
data = pd.read_csv('graf_2.4/data/FP_SNPs.txt', delimiter='\t')
data.head()

       rs#  chromosome  GB37_position  GB38_position allele1 allele2
0  2887286           1        1156131        1220751       C       T
1  6685064           1        1211292        1275912       T       C
2  2840528           1        2283896        2352457       A       G
3  3890745           1        2553624        2622185       C       T
4  1798246           1        3080855        3164291       C       A

In [16]:
data = data[['chromosome','GB38_position', 'rs#', 'allele1', 'allele2']]
data.columns = ['CHROM','POS', 'ID', 'allele1', 'allele2']

In [18]:
data['CHROM'] = data['CHROM'].apply(lambda x: 'chr' + str(x))
data['ID'] = data['ID'].apply(lambda x: 'rs' + str(x))
data.head()

  CHROM      POS         ID allele1 allele2
0  chr1  1220751  rs2887286       C       T
1  chr1  1275912  rs6685064       T       C
2  chr1  2352457  rs2840528       A       G
3  chr1  2622185  rs3890745       C       T
4  chr1  3164291  rs1798246       C       A

In [19]:
data = data[data['CHROM'] != 'chr23']

In [21]:
data

      CHROM       POS         ID allele1 allele2
0      chr1   1220751  rs2887286       C       T
1      chr1   1275912  rs6685064       T       C
2      chr1   2352457  rs2840528       A       G
3      chr1   2622185  rs3890745       C       T
4      chr1   3164291  rs1798246       C       A
...     ...       ...        ...     ...     ...
9995  chr22  49903787     rs1321       C       T
9996  chr22  50018612   rs137879       T       C
9997  chr22  50118978   rs138229       G       A
9998  chr22  50226183  rs4838865       A       G
9999  chr22  50577409  rs3213445       C       T

[10000 rows x 5 columns]

In [23]:
data.to_csv('FP_SNPs_10k_GB38_twoAllelsFormat.tsv', sep='\t', index=False)